services:
  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  poll-service:
    build: ./poll-service
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
    depends_on:
      - postgres
    ports:
      - "8080:8080"

  results-service:
    build: ./results-service
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      POLL_BASE: http://poll-service:8080
    depends_on:
      - postgres
      - poll-service
    ports:
      - "8081:8081"

  frontend:
    build: ./frontend
    depends_on:
      - poll-service
      - results-service
    ports:
      - "8082:80"

volumes:
  pgdata:
