apiVersion: apps/v1
kind: Deployment
metadata:
  name: results-service
  namespace: minipolls
spec:
  replicas: 1
  selector:
    matchLabels:
      app: results-service
  template:
    metadata:
      labels:
        app: results-service
    spec:
      containers:
        - name: results-service
          image: shreeyakalidindi/results-service:1.0.0
          env:
            - name: DB_HOST
              value: postgres
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: appdb
            - name: DB_USER
              value: appuser
            - name: DB_PASS
              value: password
            - name: POLL_BASE
              value: http://poll-service:8080
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: results-service
  namespace: minipolls
spec:
  type: ClusterIP
  selector:
    app: results-service
  ports:
    - port: 8081
      targetPort: 8081
